# Generated by Django 4.0.4 on 2022-05-24 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=180)),
                ('product_price', models.BigIntegerField(blank=True, max_length=180)),
                ('product_quantity', models.IntegerField(blank=True, default=False, max_length=180)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
