# Generated by Django 4.0.4 on 2022-05-24 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0002_cartitem_user_alter_cartitem_product_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='product_price',
            field=models.FloatField(max_length=180),
        ),
    ]
